-keep class io.hammerhead.** { *; }
-keep class io.hammerhead.descentsegs.** { *; }
-dontwarn okhttp3.**
-dontwarn okio.**
-keepattributes *Annotation*, InnerClasses
-keepclassmembers @kotlinx.serialization.Serializable class ** { *** Companion; }
